name: Wipe all clusters and apps

on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    name: Wipe all clusters and apps
    steps:
    - uses: realm/ci-actions/mdb-realm/deleteAllClusters@fac1d6958f03d71de743305ce3ab27594efbe7b7
      with:
        realmUrl: ${{ secrets.REALM_QA_BASE_URL }}
        atlasUrl: ${{ secrets.ATLAS_QA_BASE_URL }}
        projectId: ${{ secrets.ATLAS_QA_PROJECT_ID }}
        apiKey: ${{ secrets.ATLAS_QA_PUBLIC_API_KEY }}
        privateApiKey: ${{ secrets.ATLAS_QA_PRIVATE_API_KEY }}
